# Site settings
title: New Zealand Government Web Standards on GitHub
email: web.standards@dia.govt.nz
baseurl: "/web-standards" # the subpath of your site, e.g. /blog
# Site custom vars
dirs:
  'guidance':
    url: /guidance/
    title: Guidance
  'quick-reference':
    url: /guidance/quick-reference/
    title: Quick reference guides
  'online-govt-guide':
    url: /guidance/online-govt-guide/
    title: Online government guide
  'assessment-guides':
    url: /guidance/assessment-guides/
    title: Web Standards assessment guides
  'presentations':
    url: /presentations/
    title: Presentations
  'workshops':
    url: /workshops/
    title: Workshops

# Build settings
markdown: kramdown

# Exclude
exclude: ["presentations/NZ-Govt-Web-A11y-Training-2016/node_modules"]
